# Used example:
# https://github.com/vegasbrianc/github-monitoring/blob/master/docker-compose.yml

version: "3.1"

volumes:
  prometheus_data: {}

services:
  prometheus:
    image: prom/prometheus
    volumes:
     - ./prometheus_data:/prometheus_data
    command:
      - '--config.file=/prometheus_data/prometheus.yml'
    ports:
      - 9090:9090