# Used example:
# https://github.com/vegasbrianc/github-monitoring/blob/master/docker-compose.yml

version: "3.1"

services:
  server:
    build: .
    container_name: server-sms
    volumes: 
      - ./output:/root/output
      - ./dataset:/root/dataset
    ports:
      - 8080:8080
    expose:
      - "8080"

  prometheus:
    image: prom/prometheus
    container_name: prometheus-sms
    depends_on:
      - server
    volumes:
     - ./prometheus-config:/prometheus-config
     - prometheus_data:/data
    user: root
    command:
      - '--config.file=/prometheus-config/prometheus.yml'
      - '--storage.tsdb.path=/data'
    ports:
      - 9090:9090
    expose:
      - "9090"

  grafana:
    image: grafana/grafana
    container_name: grafana-sms
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-config:/grafana-config
    command:
      - '--config=/grafana-config/grafana.ini'
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
    ports:
      - 3000:3000

  renderer:
    image: grafana/grafana-image-renderer
    container_name: grafana-renderer-sms
    depends_on:
      - grafana
    ports:
      - 8081:8081


volumes:
  prometheus_data: {}
  grafana_data: {}