# Used example:
# https://github.com/vegasbrianc/github-monitoring/blob/master/docker-compose.yml

version: "3.1"

volumes:
  prometheus_data: {}

services:
  prometheus:
    image: prom/prometheus
    volumes:
     - /prometheus_data/prometheus.yml:/prometheus/prometheus.yml
    command:
      - '--config.file=/prometheus/prometheus/prometheus.yml'
    ports:
      - 9090:9090