# Used example:
# https://github.com/vegasbrianc/github-monitoring/blob/master/docker-compose.yml

version: "3.1"

services:
  server:
    build: .
    container_name: server-sms
    ports:
      - 8080:8080
    expose:
      - "8080"

  prometheus:
    image: prom/prometheus
    container_name: prometheus-sms
    volumes:
     - ./prometheus-config:/prometheus-config
     - prometheus_data:/data
    user: root
    command:
      - '--config.file=/prometheus-config/prometheus.yml'
      - '--storage.tsdb.path=/data'
    ports:
      - 9090:9090
    expose:
      - "9090"
    links:
      - alertmanager:alertmanager
    depends_on:
      - server

  grafana:
    image: grafana/grafana
    container_name: grafana-sms
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager-sms
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager-config/:/alertmanager-config
      - alertmanager_data:/data
    command:
      - '--config.file=/alertmanager-config/config.yml'
      - '--storage.path=/data'

volumes:
  prometheus_data: {}
  grafana_data: {}
  alertmanager_data: {}
