global:
  scrape_interval: 1s
  external_labels:
    monitor: 'datadrift-detection-monitor'

rule_files:
- "alerts/alert.rules"

scrape_configs:
  - job_name: 'datadrift monitoring'
    static_configs:
      - targets: ['server-sms:8080']