global:
  scrape_interval:     15s
  external_labels:
    monitor: 'datadrift-detection-monitor'

rule_files:
- "alertmanager/alert.rules"

scrape_configs:
  - job_name: 'monitoring'

    scrape_interval: 100ms

    static_configs:
      - targets: ['server-sms:8080']